[project]
name = "yp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thekurenkov", email = "ivank.04@mail.ru" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
yp = "yp:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
